var express=require('express');
var routes=express.Router();
var UserController=require('../controllers/UserController.js');
var TaskController=require('../controllers/TaskController.js');
routes.post('/addnewuser',UserController.addNewUser);
routes.post('/signin',UserController.signin);
routes.post('/get',UserController.getallUsers);
routes.post('/upload',UserController.uploadimage);
routes.post('/addnewtask',TaskController.addnewtask);
routes.post('/gettasks',TaskController.getalltasks);
routes.post('/giveupdates',TaskController.addupdates);
routes.post('/gettaskupdates',TaskController.gettaskupdates);
routes.post('/changestatus',UserController.updatecurrentstatus);
routes.post('/sample',UserController.sample);
routes.post('/updateofficelocation',UserController.updateofficelocation);
routes.post('/rehan/updatelocation',UserController.updaterehanlocation);
routes.post('/employee/updatehomelocation',UserController.updateemployeehomelocation);
routes.post('/changepassword',UserController.updatepassword);
routes.get('/employee/getrehanlocation',UserController.getrehanlocation);
routes.post('/employee/updatetaskstatus',TaskController.updatetaskstatus);
routes.get('/getallusers',UserController.getallUsers);
routes.get('/getrehan',UserController.getrehanDetails);
module.exports=routes;